[package]
name = "raw"
version = "0.0.1"
authors = ["Pepion"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3"
actix-session = "0.4"
actix-utils = "2"
env_logger = "0.8"
actix-rt = "1"
futures = "0.3.4"
futures-timer = "3.0.2"
# tokio = { version = "0.2", features = ["sync"] }
